### ISSUE TITLE
Use @match instead of @include

### ISSUE THREAD

**Issue by iwconfig** [makise-homura/watch-youtube-shorts-as-normal-videos#1]
Tampermonkey has the following deprecation warning:

> eslint: userscripts/better-use-match - Using @include is potentially unsafe and may be obsolete in Manifest v3 in early 2023. Please switch to @match.

**Comment by makise-homura** [comment]
Fixed in b6ec5785092e5ce5f332b71955293af0378ee43f. Thanks for suggestion.
