### ISSUE TITLE
Improve speed with @run-at document-start

### ISSUE THREAD

**Issue by iwconfig** [makise-homura/watch-youtube-shorts-as-normal-videos#2]
Running the script at `document-start` means the location change occurs earlier, by loading the script before anything else.

Please consider adding

```
// @run-at document-start
```

to the metadata block.

Thanks a lot btw!

**Comment by makise-homura** [comment]
Fixed in 7e7284e35471b23316af03826e495bde29866ea9. Thanks for suggestion, now it really works faster!
